### ISSUE TITLE
The older messages are not getting deleted.

### ISSUE THREAD

**Issue by midhunexeter** [gurland/telegram-delete-all-messages#51]

**Comment by ithelor** [comment]
I had the same issue. Ran the script through a number of groups and got different results in terms of messages found: from precisely 10k to over 20k. So in my case if there's more than 10k messages the script wasn't able to handle all of them in one run. Probably has something to do with Telegram's limitations, since sometimes even the client was unable to find the rest of the messages.

Either way the issue resolves itself in about 5-10 minutes. Just give it some rest and then run the script again.

**Comment by midhunexeter** [comment]
Okay. Thank you for the reply.
