### ISSUE TITLE
Sorry if this is a bad way to ask

### ISSUE THREAD

**Issue by musterintu** [gurland/telegram-delete-all-messages#61]
I didnt know who else to ask but I was wondering if you guys could make a similar python script to remove all members from all of your groups and channels. So you keep your groups but remove everyone else in them.

**Comment by gurland** [comment]
Hello! Thank you for your feature request, but unfortunately this is out of the scope of this project. 

I will provide some useful reference documentation tho! You may fork our project and then modify it so that you:

1. Get all groups and check whether you are an admin there:
  - `me = app.get_chat_member(chat_id, app.get_me().id)` and if `me.status in ("administrator", "creator")` then goto 2.
2. [Get all members](https://docs.pyrogram.org/api/methods/get_chat_members) from your group 
3. Remove users one by one using this [method](https://docs.pyrogram.org/api/methods/ban_chat_member#pyrogram.Client.ban_chat_member)
